#!/bin/sh
# SPDX-License-Identifier: GPL-2.0

TARGET=$1
ARCH=$2
SMP=$3
CC=$4
srctree=$5

# If compile.h exists already and we don't own autoconf.h
# (i.e. we're not the same user who did make *config), don't
# modify compile.h
# So "sudo make install" won't change the "compiled by <user>"
# do "compiled by root"

if [ -r $TARGET -a ! -O $srctree/include/generated/autoconf.h ]; then
  exit 0
fi

# Do not expand names
set -f

# Fix the language to get consistent output
LC_ALL=C
export LC_ALL

if [ -z "$KBUILD_BUILD_VERSION" ]; then
  if [ ! -f "$srctree/.version" ]; then
    VERSION=1
  else
	  VERSION=$(expr $(cat $srctree/.version 2>/dev/null || echo 1) + 1)
  fi
else
	VERSION=$KBUILD_BUILD_VERSION
fi

if [ -z "$KBUILD_BUILD_TIMESTAMP" ]; then
	TIMESTAMP=`date`
else
	TIMESTAMP=$KBUILD_BUILD_TIMESTAMP
fi
if test -z "$KBUILD_BUILD_USER"; then
	KERNEL_COMPILE_BY=$(whoami | sed 's/\\/\\\\/')
else
	KERNEL_COMPILE_BY=$KBUILD_BUILD_USER
fi
if test -z "$KBUILD_BUILD_HOST"; then
	KERNEL_COMPILE_HOST=`hostname`
else
	KERNEL_COMPILE_HOST=$KBUILD_BUILD_HOST
fi

UTS_VERSION="#$VERSION"
CONFIG_FLAGS=""
if [ -n "$SMP" ] ; then CONFIG_FLAGS="SMP"; fi
CONFIG_FLAGS="$CONFIG_FLAGS PREEMPT"
UTS_VERSION="$UTS_VERSION $CONFIG_FLAGS $TIMESTAMP"

# Truncate to maximum length

UTS_LEN=64
UTS_TRUNCATE="cut -b -$UTS_LEN"

# Generate a temporary compile.h

( echo /\* This file is auto generated, version $VERSION \*/
  if [ -n "$CONFIG_FLAGS" ] ; then echo "/* $CONFIG_FLAGS */"; fi

  echo \#ifndef __KERNEL_VERSION__
  echo \#error "Not available KERNEL_VERSION"
  echo \#endif

  echo \#define UTS_MACHINE \"$ARCH\"

  echo \#define UTS_VERSION \"`echo $UTS_VERSION | $UTS_TRUNCATE`\"

  echo \#define KERNEL_COMPILE_BY \"`echo $KERNEL_COMPILE_BY | $UTS_TRUNCATE`\"
  echo \#define KERNEL_COMPILE_HOST \"`echo $KERNEL_COMPILE_HOST | $UTS_TRUNCATE`\"

  echo \#define KERNEL_COMPILER \"`$CC -v 2>&1 | grep ' version ' | sed 's/[[:space:]]*$//'`\"
) > .tmpcompile

# Only replace the real compile.h if the new one is different,
# in order to preserve the timestamp and avoid unnecessary
# recompilations.
# We don't consider the file changed if only the date/time changed.
# A kernel config change will increase the generation number, thus
# causing compile.h to be updated (including date/time) due to the
# changed comment in the
# first line.

if [ -r $srctree/.tmp_trigger_depends ]; then
   mv -f .tmpcompile $TARGET
fi
rm -f .tmpver.1 .tmpver.2 $srctree/.tmp_trigger_depends
